import dellXp from "../assets/images/dell/1.jpg";
import macBookPro from "../assets/images/macbook/1.jpg";
import macBook13 from "../assets/images/macbook_13/1.jpg";

export const products = [
  {
    id: 1,
    name: "Dell XPS 17 17.0 inch",
    description:
      "Meet the new Dell XPS 17 - a 17-inch laptop designed to power your next big idea. Featuring 13th Gen Intel® Core™ processors, NVIDIA GeForce RTX 40 Series graphics and a studio-quality display. ",
    category: "Electronics",
    price: 2899.99,
    ratings: 4.2,
    total_ratings: 72,
    image: dellXp,
  },
  {
    id: 2,
    name: "Product B",
    description: "This is a description for Product B.",
    category: "Clothing",
    price: 39.99,
    ratings: 4.6,
    total_ratings: 75,
    image: macBook13,
  },
  {
    id: 3,
    name: "Product C",
    description: "This is a description for Product C.",
    category: "Decor",
    price: 199.99,
    ratings: 3.4,
    total_ratings: 150,
    image: "product_c.jpg",
  },
  {
    id: 4,
    name: "Apple - MacBook Pro 14",
    description:
      "The 14-inch MacBook Pro blasts forward with M3 Pro and M3 Max, radically advanced chips that drive even greater performance for more demanding workflows",
    category: "Electronics",
    price: 1849.99,
    ratings: 4.9,
    total_ratings: 688,
    image: macBookPro,
  },
  {
    id: 5,
    name: "Product E",
    description: "This is a description for Product E.",
    category: "Clothing",
    price: 29.99,
    ratings: 3.0,
    total_ratings: 90,
    image: "product_e.jpg",
  },
  {
    id: 6,
    name: "Product F",
    description: "This is a description for Product F.",
    category: "Electronics",
    price: 599.99,
    ratings: 4.6,
    total_ratings: 180,
    image: "product_f.jpg",
  },
  {
    id: 7,
    name: "Product G",
    description: "This is a description for Product G.",
    category: "Decor",
    price: 249.99,
    ratings: 4.9,
    total_ratings: 200,
    image: "product_g.jpg",
  },
  {
    id: 8,
    name: "Product H",
    description: "This is a description for Product H.",
    category: "Clothing",
    price: 49.99,
    ratings: 2.3,
    total_ratings: 60,
    image: "product_h.jpg",
  },
  {
    id: 9,
    name: "Product I",
    description: "This is a description for Product I.",
    category: "Electronics",
    price: 899.99,
    ratings: 4.8,
    total_ratings: 150,
    image: "product_i.jpg",
  },
  {
    id: 10,
    name: "Product J",
    description: "This is a description for Product J.",
    category: "Decor",
    price: 179.99,
    ratings: 4.7,
    total_ratings: 130,
    image: "product_j.jpg",
  },
  {
    id: 11,
    name: "Product K",
    description: "This is a description for Product K.",
    category: "Electronics",
    price: 349.99,
    ratings: 4.5,
    total_ratings: 100,
    image: "product_k.jpg",
  },
  {
    id: 12,
    name: "Product L",
    description: "This is a description for Product L.",
    category: "Clothing",
    price: 59.99,
    ratings: 4.2,
    total_ratings: 75,
    image: "product_l.jpg",
  },
  {
    id: 13,
    name: "Product M",
    description: "This is a description for Product M.",
    category: "Decor",
    price: 299.99,
    ratings: 4.8,
    total_ratings: 150,
    image: "product_m.jpg",
  },
  {
    id: 14,
    name: "Product N",
    description: "This is a description for Product N.",
    category: "Electronics",
    price: 699.99,
    ratings: 4.7,
    total_ratings: 120,
    image: "product_n.jpg",
  },
  {
    id: 15,
    name: "Product O",
    description: "This is a description for Product O.",
    category: "Clothing",
    price: 34.99,
    ratings: 4.0,
    total_ratings: 90,
    image: "product_o.jpg",
  },
  {
    id: 16,
    name: "Product P",
    description: "This is a description for Product P.",
    category: "Electronics",
    price: 549.99,
    ratings: 4.6,
    total_ratings: 180,
    image: "product_p.jpg",
  },
  {
    id: 17,
    name: "Product Q",
    description: "This is a description for Product Q.",
    category: "Decor",
    price: 199.99,
    ratings: 4.9,
    total_ratings: 200,
    image: "product_q.jpg",
  },
  {
    id: 18,
    name: "Product R",
    description: "This is a description for Product R.",
    category: "Clothing",
    price: 44.99,
    ratings: 4.3,
    total_ratings: 60,
    image: "product_r.jpg",
  },
  {
    id: 19,
    name: "Product S",
    description: "This is a description for Product S.",
    category: "Electronics",
    price: 999.99,
    ratings: 4.8,
    total_ratings: 150,
    image: "product_s.jpg",
  },
  {
    id: 20,
    name: "Product T",
    description: "This is a description for Product T.",
    category: "Decor",
    price: 159.99,
    ratings: 4.7,
    total_ratings: 130,
    image: "product_t.jpg",
  },
];
